---
- hosts: all
  become: yes
  tasks: 
  - name: I want to install webserver on ansible ubuntu node
    apt:
      name: apache2
      state: present

  - name: I want to install git
    apt:
      name: git
      state: present

  # - name: I want to install python

  # - name:
  