---
- hosts: 172.31.40.246 
  become: yes
  tasks:
  - name: I want to create a file on node side 
    file: 
      path: /home/ubuntu/testfile
      state: touch 

  - include_tasks: myfile.yml

  # OR we can use import_tasks
  
  # - import_tasks: myfile.yml