---
- hosts: all
  become: yes
  tasks:
  - name: install webserver apache2
    apt:
      name: apache2
      state: present

# to start a service
  - name: I want to start webserver
    service: 
      name: apache2
      state: started
    when: ansible_os_family == "Debian"