---
- hosts: myWebServers
  become: yes
  tasks:
  - name: install webserver apache2
    apt:
      name: "{{myUbuntuWebPack}}"
      state: "{{state}}"
  
  - name: install git on webserver
    apt:
      name: "{{gitWebPack}}"
      state: "{{state}}"

# to start a service
  - name: I want to start webserver
    service: 
      name: apache2
      state: started
    when: ansible_os_family == "Debian"