---
# tasks file for mywebrole
- name: I want to install webserver
  apt:
    name: apache2
    state: present

- name: I want to install tree
  apt:
    name: tree 
    state: present 

- name: I want to copy j2 file to index file
  template:
    src: template/myindex.j2
    dest: /var/www/html/index.html